name: 10mins-cron
on:
  schedule:
    - cron: '* * 1 * *'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Add a job
        run: |
          curl --request POST \
          --url 'https://remix-mongodb-auth.vercel.app/hello' \
